export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_CART = "SET_CART";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const APPEND_PRODUCTS = "APPEND_PRODUCTS";
export const GENERATE_CHECKOUT_TOKEN = "GENERATE_CHECKOUT_TOKEN";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const SET_CHECKOUT = "SET_CHECKOUT";
